param(
    [switch]$IncludeDotnetClean,
    # Removes repo-root artifacts/ (native CMake output, dev-stack logs, testbench screenshots — all regenerated by builds/scripts).
    [switch]$IncludeArtifacts,
    [switch]$WhatIf
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $repoRoot

Write-Host "Cleaning build outputs in: $repoRoot"

if ($IncludeArtifacts) {
    $artifactsRoot = Join-Path $repoRoot "artifacts"
    if (Test-Path $artifactsRoot) {
        if ($WhatIf) {
            Write-Host "[WhatIf] Remove entire directory: $artifactsRoot"
        } else {
            Remove-Item -Path $artifactsRoot -Recurse -Force -ErrorAction Stop
            Write-Host "Removed $artifactsRoot"
        }
    } else {
        Write-Host "No artifacts\ directory at repo root."
    }
}

$targetNames = @("bin", "obj", "TestResults")
$targets = Get-ChildItem -Path $repoRoot -Directory -Recurse -Force |
    Where-Object { $targetNames -contains $_.Name }

if ($targets.Count -eq 0) {
    Write-Host "No build artifact directories found."
} else {
    foreach ($target in $targets) {
        if ($WhatIf) {
            Write-Host "[WhatIf] Remove $($target.FullName)"
            continue
        }

        Remove-Item -Path $target.FullName -Recurse -Force -ErrorAction Stop
        Write-Host "Removed $($target.FullName)"
    }
}

if ($IncludeDotnetClean) {
    $dotnet = Get-Command dotnet -ErrorAction SilentlyContinue
    if ($null -eq $dotnet) {
        Write-Host "dotnet not found on PATH; skipping dotnet clean."
    } else {
        foreach ($config in @("Debug", "Release")) {
            Write-Host "Running: dotnet clean TalosForge.sln -c $config"
            dotnet clean TalosForge.sln -c $config | Out-Host
        }
    }
}

$gitCmd = Get-Command git -ErrorAction SilentlyContinue
if ($null -ne $gitCmd) {
    Write-Host ""
    Write-Host "Git status:"
    & git status --short --branch | Out-Host
} else {
    Write-Host "git not found on PATH; skipping git status."
}
